---
- name: log in to openshift
  command: oc --insecure-skip-tls-verify login https://{{oc_host}}:{{oc_port }} -u {{oc_user }} -p {{ oc_password }}

- name: use the correct project
  command: oc --insecure-skip-tls-verify  project {{  project_name }}

- name: Delete the Jenkins Deployment via local file
  command: oc --insecure-skip-tls-verify  delete -f "{{ role_path }}/../ocpdemo/files/jenkins-ephemeral.yaml"
  ignore_errors: yes

- name: log out of openshift
  command:  oc --insecure-skip-tls-verify logout
  when: False
  
