---
- name: log in to openshift
  command: oc --insecure-skip-tls-verify  login https://{{oc_host}}:{{oc_port }} -u {{oc_user }} -p {{ oc_password }}

- name: create the deepwells project
  command: oc --insecure-skip-tls-verify  new-project {{  project_name }}
  ignore_errors: yes

# Raw Openshift requires python code not in the repo
-  name: Create a kubernetes namespace
   openshift_raw:
     api_version: v1
     kind: Project
     name: "{{ project_name }}"
     description: "{{ project_name }}"
     display_name: "{{ project_name }}"
     state: present
     username:  "{{oc_user }}"
     password:  "{{ oc_password }}"
   when: False

- name: use the deepwells project
  command: oc --insecure-skip-tls-verify  project {{  project_name }}

- name: Create a Jenkins Deployment by reading the definition from a local file
  command: oc --insecure-skip-tls-verify  create -f "{{ role_path }}/files/jenkins-ephemeral.yaml"

# logging out of openshift invalidates the token
- name: log out of openshift
  command:  oc --insecure-skip-tls-verify logout
  when: False

# Ideally, we would use the openshift_raw module, but it does not yet
# handle the APIs we need to deploy the reified template
- name: Create a Jenkins Deployment by reading the definition from a local file
  openshift_raw:
    state: present
    src: "{{ role_path }}/files/jenkins-ephemeral.yaml"
  when: False






